config/routes.rb
Rails.application.routes.draw do
#  ルート
  root 'top#index'
#  サインアップサインインルーティング
  devise_for :users

        #コントローラ               アクション		
  resources :list, only: %i(new create edit update destroy) do
# 			/list/:list_id/card/new	
#             /list/:list_id/card
    resources :card, only: %i(new create show edit update destroy) do
    resources :card, except: %i(index)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
# 　　カードタイトル、詳細、誰が投稿したか
class Card < ApplicationRecord
# 　　カードはリストに属する
  belongs_to :list
# 　タイトル　　長さ
  validates :title, length: { in: 1..255 }
# 　詳細　　長さ
  validates :memo,  length: { maximum: 1000 }
end

app/models/list.rb
class List < ApplicationRecord
    # リストはユーザに属する
  belongs_to :user
        # 		リストタトル　長さ　1~255
 validates :title, length: { in: 1..255 }
# たくさん持てる　カード
  has_many :cards, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # 　複数リスト作成可能　ユーザ消したらリストも消す
  has_many :lists, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
          # 検証　　　名前　　存在する　　　　長さ　　　　　20
  validates :name, presence: true, length: { maximum: 20 }
end

app/controllers/application_controller.rb
# 　　　全コントローラ
class ApplicationController < ActionController::Base
# 　　セキュリティ
   protect_from_forgery with: :exception
# アクション実行前					サインインしていないならサインインページにリダイレクト
  before_action :authenticate_user!
# アクション実行前　　　ストロングパラメータ　　　もし　デバイスコントローラを使う時
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
        #  ストロングパラメータ
    def configure_permitted_parameters
							# 		許可　　サインアップの時　　名前ƒ
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
								# 	許可　　　アカウントアップデートの時　名前
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end

end

app/controllers/card_controller.rb
class CardController < ApplicationController

  def new
# 		カードタイトル、詳細、誰が投稿したか　作る
    @card = Card.new
# 　　リストタイトル　誰が投稿したか　見つける　id
    @list = List.find_by(id: params[:list_id])
  end

  def create
    #  カードタイトル、詳細、誰が投稿したか 作る　　カードタイトル、詳細、誰が投稿したか　取得
    @card = Card.new(card_params)
# 保存
    if @card.save
      redirect_to :root
# 失敗
    else
      render action: :new
    end
  end
# 　詳細
  def show
# カードタイトル、詳細、誰が投稿したか　見つける　id　
    @card = Card.find_by(id: params[:id])
  end

# カード編集
  def edit
# カードタイトル、詳細、誰が投稿したか	　見つける　id
    @card = Card.find_by(id: params[:id])
# リストタイトル　誰が投稿したか　user_idがcurretn_user.idと一致するレコードの情報を取得　　　　　
    @lists = List.where(user: current_user)

  end

# カード編集
  def update
# カードタイトル、詳細、誰が投稿したか　見つける　id
    @card = Card.find_by(id: params[:id])
#   カードタイトル、詳細、誰が投稿したか 更新　カードタイトル、詳細、誰が投稿したか
    if @card.update_attributes(card_params)
# カード一覧
      redirect_to :root

    else
   # カード編集
      render action: :edit
    end
  end
# カード削除
  def destroy
    @card = Card.find_by(id: params[:id])
# カードタイトル、詳細、誰が投稿したか　消去
    @card.destroy
    redirect_to :root
  end


  private
# カードタイトル、詳細、誰が投稿したか
    def card_params
								# 		カードタイトル、詳細、誰が投稿したか
      params.require(:card).permit(:title, :memo, :list_id)
    end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
# 　　モデル　見つける　id 
  before_action :set_list, only: %i(edit update destroy)

# リスト作成画面
  def new
    #  		モデル　作る
    @list = List.new
  end 

  def create
      # 　モデル　作る　
    @list = List.new(list_params)
# 　もし　モデル　保存
    if @list.save
# 　　行く　　　ルート
      redirect_to :root
# 保存失敗
    else
# 　　　リスト作成画面
      render action: :new
    end
  end

#  　編集
  def edit

  end
# 更新
  def update

#  もし　　　更新　　　　　　
    if @list.update_attributes(list_params)
# 　　リダイレクト　ルート
      redirect_to :root
# 　それ以外は
    else
        # 　アクション
      render action: :edit
    end
  end
# リスト消去
  def destroy
# 　　リスト消去
    @list.destroy
# 　　リスト一覧へ
    redirect_to :root
  end
  

  private
    def list_params
				# 	リストモデル　タイトル　　　　　誰がリストを作成したか
      params.require(:list).permit(:title).merge(user: current_user)
    end
# モデル　見つける　id
    def set_list
# 			モデル　見つける　id
      @list = List.find_by(id: params[:id])
    end

end

app/controllers/top_controller.rb
# 　　　コントローラ
class TopController < ApplicationController
# リスト表示
  def index
     # モデル　　　　　現在ユーザ　　並べる　 作成順
    @lists = List.where(user: current_user).order("created_at ASC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/card/edit.html.erb
<div class="cardeditPgae">
  <div class='container'>
    <%= form_with model: @card, url: { action: :update }, html: { class: 'cardeditForm' }, local: true do |f| %>
      <% if @card.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
    <!--カード名-->
      <div class="cardeditForm_title">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", placeholder: "カード名" %>
      </div>
　　<!--詳細-->
      <div class="cardeditForm_memo">
        <%= f.label :memo %>
        <%= f.text_area :memo, class: "form-control", placeholder: "詳細" %>
      </div>
<!--カード動かす-->
      <div class="cardeditForm_memo">
        <label>リスト名</label>
        <%= select :card, :list_id, @lists.map{ |l| [l.title, l.id] }, {}, { class: 'form-control' } %>
      </div>

　<!--更新ボタン-->
      <div class="text-center"><%= f.submit "更新する", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/card/new.html.erb
	<!--カードタイトル、詳細-->
<div class="cardnewPgae">
  <div class='container'>
    <%= form_with model: @card, url: { action: :create }, html: { class: 'cardnewForm' }, local: true do |f| %>
      <%= f.hidden_field :list_id, value: @list.id %>
<!--エラー-->
      <% if @card.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <div class="cardnewForm_title">
<!--カードタイトル-->
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true, class: "form-control", placeholder: "カード名" %>
      </div>
<!--カード詳細-->
      <div class="cardnewForm_memo">
        <%= f.label :memo %>
        <%= f.text_area :memo, autofocus: true, class: "form-control", placeholder: "詳細" %>
      <div class="text-center"><%= f.submit "作成する", class: "submitBtn" %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/card/show.html.erb
<!--詳細ビュー-->
<div class='carddetailPage'>
  <div class="container">
    <div class="cardContents">
      <div class="cardContents_title">
<!--カードタイトル-->
        <div>タイトル</div>
        <h2><%= @card.title %></h2>
      </div>
<!--カードメモ-->
      <div class="cardContents_memo">
        <div>メモ</div>
        <div><%= @card.memo %></div>
      </div>
<!--カードリスト名-->
      <div class="cardContents_listStatus">
        <div>リスト名</div>
        <div><%= @card.list.title %></div>
      </div>
<!--カード編集-->
      <div class="cardContents_btnArea">
        <%= link_to '編集する', edit_list_card_path(@card.list, @card), class: "edit_btn" %>
      </div>
<!--カード消去-->
        <%= link_to '削除をする', list_card_path(@card.list, @card), class: "text-danger delete_btn", method: :delete, data: { confirm: "このカードを削除して大丈夫ですか?" } %>


    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>kanban</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダー　　　　　　　　　もし　ログインしていたら-->
    <%= render 'partial/header' if current_user %>
<!--フラッシュメッセ-->
    <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
<!--フラッシュメッセ-->
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/list/edit.html.erb
<!--リスト編集画面-->
<div class="listeditPage">
  <div class="container">
    <%= form_with model: @list, url: { action: :update }, html: { class: 'listForm' }, local: true do |f| %>
　<!--リスト　エラー-->
      <% if @list.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
　　<!--タイトル-->
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control listName", placeholder: "リスト名" %>
      <div class="text-center"><%= f.submit "編集する", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/list/new.html.erb
<!--リスト作成画面-->
<div class="listnewPage">
  <div class="container">
    <%= form_with model: @list, url: { action: :create }, class: "new_list", local: true do |f| %>
      <% if @list.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <!--タイトル-->
      <%= f.label :title %>
	   <!--タイトル-->
      <%= f.text_field :title, autofocus: true, class: "form-control listName", placeholder: "リスト名" %>
      <div class="text-center"><%= f.submit "作成", class: "submitBtn" %></div>ß
    <% end %>
  </div>
</div>

app/views/partial/_header.html.erb
<!--ヘッダー-->
<header class="header">
  <nav class="nav">
    <ul class="header_menu">
								<!--ログインユーザ　名前-->
      <li class="nav-link"><%= current_user.name %>さん</li>
      <li class="header_menu_title"><%= link_to "kanban", root_path, class: "nav-link" %></li>
      <li>
        <ul class="header_menu_inner">
                                                                <!--リスト作成-->
          <li><%= link_to "リストを作成", new_list_path, class: "nav-link listNew" %></li>
												<!--サインアウト-->
          <li><%= link_to "サインアウト", destroy_user_session_path, class: "nav-link", method: :delete %></li>

        </ul>
      </li>
    </ul>
  </nav>
</header>

app/views/top/index.html.erb
<!--リスト表示デザイン-->

<div class="topPage">
  <div class="listWrapper">
   <!--繰り返す-->
    <% @lists.each do |list| %>
      <div class="list">
        <div class="list_header">
											<!--タイトル-->
          <h2 class="list_header_title"><%= list.title %></h2>
          <div class="list_header_action">
           <!--消去リンク-->
            <%= link_to content_tag(:i, '', class: 'fas fa-trash'), list, method: :delete, data: { confirm: "#{list.title}を削除して大丈夫ですか？" } %>
				<!--編集リンク-->
            <%= link_to(content_tag(:i, '', class: 'fas fa-pen'), edit_list_path(list)) %>
          </div>          
        </div>
        <div class="cardWrapper">
           <!--三本線-->
          <% list.cards.each do |card| %>
            <%= link_to list_card_path(list, card), class:"cardDetail_link" do %>
              <div class="card">
                <h3 class="card_title"><%= card.title %></h3>
               <!--何か書いてあれば-->
                <% if card.memo.size > 0 %>
              <!--詳細-->
                  <div class="card_detail is-exist"><i class="fas fa-bars"></i></div>
                <% end %>
              </div>
            <% end %>

          <% end %>

          <div class="addCard">
            <i class="far fa-plus-square"></i>
            <%= link_to "さらにカードを追加", new_list_card_path(list), class: "addCard_link" %>
          </div>
        </div>

      </div>
    <% end %>
  </div>
</div>